$schema: "1.0"
name: "devbox-customization"
tasks:
  - name: dsc
    description: "hello, world"
    parameters:
      configurationPath: 'inline'
      inlineConfiguration: |
        $schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2024/04/config/document.json
        resources:
        - name: current user registry
          type: Microsoft.Windows/Registry
          properties:
            keyPath: HKCU\Software\Microsoft\Windows\CurrentVersion\
            valueName: Run
            valueData: "C:\Windows\System32\notepad.exe"
            _ensure: Present